BookStore/Controllers/OrderController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repo { get; set; }
        private Basket basket { get; set; }

        public OrderController (IOrderRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Order());
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = basket.Items.ToArray();
                repo.SaveOrder(order);
                basket.ClearBasket();

                return RedirectToPage("/Confirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

BookStore/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Infrastructure;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public CartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove (int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

BookStore/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/Views/Shared/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
namespace Views.Shared.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket Basket;
        public CartSummaryViewComponent(Basket basketService)
        {
            Basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(Basket);
        }
    }
}

BookStore/Pages/Cart.cshtml
@page
@model BookStore.Pages.CartModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Book.Price</td>
                <td>$@((i.Quantity * i.Book.Price).ToString())</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="BookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
</div>

BookStore/Pages/Confirmation.cshtml
@page
@model BookStore.Pages.ConfirmationModel
@{
}

<div class="text-center">
    <h2>Thanks! Your book order has been received!</h2>
    <a asp-controller="Home" class="btn btn-primary">Return Home</a>
</div>

BookStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header class="bg-dark text-white p-2">
        <h1 class="navbar-brand m-lg-2">Matt Perry's Online Bookstore</h1>
        <p>Full of Professor Hilton's favorite books</p>
        <div>
            <vc:cart-summary />
        </div>
    </header>
    <div class="row m-1 p-1">
        <div>
            @RenderBody()
        </div>
    </div>
    <footer class="bg-light text-center text-lg-start">
        
        <div class="container p-4">
            
            <div class="row">
                
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#!" class="text-dark">Some Books</a>
                        </li>
                        <li>
                            <a href="#!" class="text-dark">Some More Books</a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            2022 Matt Perry
        </div>

    </footer>
    <script src="~/lib/js/bootstrap.min.js"></script>
    <script src="~/lib/js/script.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
</body>
</html>