BookStore/Components/TypesViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

BookStore/Views/Shared/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
namespace Views.Shared.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket Basket;
        public CartSummaryViewComponent(Basket basketService)
        {
            Basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(Basket);
        }
    }
}

BookStore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

@*BOOTSTRAP ADDITION #2
Font weight light and bold added to title and isbn*@
<tr class="hover-shadow">
    <td class="font-weight-bold">@Model.Title</td>
    <td>@Model.Author</td>
    <td>@Model.Publisher</td>
    <td class="font-weight-light">@Model.Isbn</td>
    <td>@Model.Classification</td>
    <td>@Model.Category</td>
    <td>@Model.PageCount</td>
    <td class="bg-info">$@Model.Price</td>
    <td>
        <form method="post" asp-page="/Cart">
            <input type="hidden" asp-for="@Model.BookId"/>
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">+</button>
            </span>
        </form>
    </td>
</tr>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/js/bootstrap.min.js"></script>
</head>
<body>
    <header class="bg-dark text-white p-2">
        <h1 class="navbar-brand m-lg-2">Matt Perry's Online Bookstore</h1>
        <p>Full of Professor Hilton's favorite books</p>
        <div>
            <vc:cart-summary />
        </div>
    </header>
    <div>
        <div class="row m-1 p-1">
            <div id="types" class="col-3">
                <vc:types></vc:types>
            </div>
            <div class="col-9">
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>
        <footer class="bg-light text-center text-lg-start">

            <div class="container p-4">

                <div class="row">

                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-dark">Some Books</a>
                            </li>
                            <li>
                                <a href="#!" class="text-dark">Some More Books</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                2022 Matt Perry
            </div>

        </footer>
    </div>
    
    <script src="~/lib/js/script.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
</body>
</html>